handlers:
- url: '/first-steps/'
  static_files: 'first-steps/index.html'
  upload: '.*'
- url: '/working-as-team/'
  static_files: 'working-as-team/index.html'
  upload: '.*'
- url: '/'
  static_files: 'index.html'
  upload: '.*'
- url: '/'
  static_dir: '/'
