handlers:
- url: '/primeros-pasos/'
  static_files: 'primeros-pasos/index.html'
  upload: '.*'
- url: '/trabajando-en-equipo/'
  static_files: 'trabajando-en-equipo/index.html'
  upload: '.*'
- url: '/autenticacion-y-hosting/'
  static_files: 'autenticacion-y-hosting/index.html'
  upload: '.*'
- url: '/ejemplos/'
  static_files: 'ejemplos/index.html'
  upload: '.*'
- url: '/'
  static_files: 'index.html'
  upload: '.*'
- url: '/'
  static_dir: '/'
