handlers:
- url: '/primeros-pasos/'
  static_files: 'primeros-pasos/index.html'
  upload: '.*'
- url: '/trabajando-en-equipo/'
  static_files: 'trabajando-en-equipo/index.html'
  upload: '.*'
- url: '/practica/'
  static_files: 'practica/index.html'
  upload: '.*'
- url: '/'
  static_files: 'index.html'
  upload: '.*'
- url: '/'
  static_dir: '/'
